### ISSUE TITLE
index.js: get(key) method in LRUCache class return -1,  it's incorrect

### ISSUE THREAD

**Issue by vunhphong** [nc-minh/technical-tips#1]

**Comment by nc-minh** [comment]
OK. 
- In main function return 0 or exit(0) are same but if you write exit(0) in different function then you program will exit from that position.
returning different values like return 1 or return -1 means that program is returning error(Because in C/C++ haven't boolean variable will return -1 means that program is returning error).

**Comment by nc-minh** [comment]
Should return null, because if return -1 there may be case key = -1, return -1 that is not true for js.
